config/routes.rb
Rails.application.routes.draw do
  # Auto generates all routes for Books CRUD
  resources :books

  # Set root to book listing
  root "books#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.order(:title)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author, :isbn, :owned_onm, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<section id="<%= dom_id book %>" class="book">
  <table>
    <tbody>
      <tr><th>Title</th><td><%= book.title %></td></tr>
      <tr><th>Author</th><td><%= book.author %></td></tr>
      <tr><th>Owned Since</th><td><%= book.owned_on %></td></tr>
      <tr><th>ISBN</th><td><%= book.isbn %></td></tr>
      <tr><th>Notes</th><td><%= @book.notes.presence || "None" %></td></tr>
    </tbody>
  </table>
</section>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <section id="book-form" class="book">
    <table>
      <tbody>
        <tr>
          <th><%= form.label :title %></th>
          <td><%= form.text_field :title %></td>
        </tr>
        <tr>
          <th><%= form.label :author %></th>
          <td><%= form.text_field :author %></td>
        </tr>
        <tr>
          <th><%= form.label :isbn %></th>
          <td><%= form.text_field :isbn %></td>
        </tr>
        <tr>
          <th><%= form.label :owned_on %></th>
          <td><%= form.date_field :owned_on %></td>
        </tr>
        <tr>
          <th><%= form.label :notes %></th>
          <td><%= form.text_area :notes, rows: 5 %></td>
        </tr>
      </tbody>
    </table>
  </section>

  <section id="actions">
    <%= form.submit %>
  </section>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<section id="navigation">
  <%= link_to "Back to books", books_path %>
</section>

<%= render "form", book: @book %>

app/views/books/index.html.erb
<% content_for :title, "Book List | Bookmark" %>

<h1>Books</h1>

<section id="notice">
  <%= notice %>
</section>

<section id="options">
  <%= link_to "New book", new_book_path %>
</section>

<section id="books">
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Owned Since</th>
        <th>ISBN</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.author %></td>
          <td><%= book.owned_on %></td>
          <td><%= book.isbn %></td>
          <td><%= link_to "View", book %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/books/new.html.erb
<h1>New book</h1>

<section id="navigation">
  <%= link_to "Back to books", books_path %>
</section>

<%= render "form", book: @book %>

app/views/books/show.html.erb
<% content_for :title, "#{@book.title} | Bookmark" %>

<h1><%= @book.title %></h1>

<section id="navigation">
  <%= link_to "Back to books", books_path %>
</section>

<section id="notice">
  <%= notice %>
</section>

<section id="options">
  <%= link_to "Edit book", edit_book_path(@book) %>
</section>

<%= render @book %>

<section id="secondary-options">
  <%= button_to "Delete book", @book, method: :delete, data: { confirm: "Are you sure you want to delete this book?" }, class: "delete" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Bookmark" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section id="page">
      <%= yield %>

      <section id="footer">
        <p>Bookmark by <a href="http://ruscoe.org/" title="Dan Ruscoe" target="_blank">Dan Ruscoe</a></p>
      </section>
    </section>
  </body>
</html>